env:
  browser: true
  es2021: true
extends:
  - airbnb
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  semi: ["error", "never"]
  react/jsx-filename-extension: [1, { "extensions": [".jsx", ".tsx"] }]
